/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/pages/about/index.vue')['default']
    App: typeof import('./src/App.vue')['default']
    CarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    Cart: typeof import('./src/components/cart.vue')['default']
    ClientLayout: typeof import('./src/layouts/ClientLayout.vue')['default']
    ICarbonAccessibility: typeof import('~icons/material-symbols/carbon-accessibility')['default']
    IHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
    IIcBaselinePerson: typeof import('~icons/ic/baseline-person')['default']
    IMaterialSymbolsHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
    IMdiAccountBox: typeof import('~icons/material-symbols/mdi-account-box')['default']
    Layout: typeof import('./src/layouts/Layout.vue')['default']
    MaterialSymbolsHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
    MsAccountBox: typeof import('~icons/material-symbols/account-box')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    Pages: typeof import('./src/pages/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
